export default {
    GOT_USER_TOKEN:'GOT_USER_TOKEN',
    LOGGED_OUT:'LOGGED_OUT',
    LOGIN_STARTED:"LOGIN_STARTED",
    LOGIN_ERROR:"LOGIN_ERROR",
    PASSWORD_CHANGED:"PASSWORD_CHANGED",
    PASSWORD_CHANGED_ERROR:"PASSWORD_CHANGED_ERROR",
    FORGOTPASSWORD:"FORGOTPASSWORD",
    REGISTER_MSG:"REGISTER_MSG"
}
